--- #YAML:1.0
name:                Email-MIME-Modifier
version:             1.442
abstract:            Modify Email::MIME Objects Easily
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::MessageID:              1.2
    Email::MIME:                   1.82
    Email::MIME::ContentType:      1.0
    Email::MIME::Encodings:        1.3
    Email::Simple:                 1.92
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
