# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME-Modifier
version:      1.42
version_from: lib/Email/MIME/Modifier.pm
installdirs:  site
requires:
    Email::MessageID:              1.2
    Email::MIME:                   1.82
    Email::MIME::ContentType:      1.0
    Email::MIME::Encodings:        1.3
    Email::Simple:                 1.92
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24
