# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME-Modifier
version:      1.1
version_from: lib/Email/MIME/Modifier.pm
installdirs:  site
requires:
    Email::MessageID:              
    Email::MIME:                   1.7
    Email::MIME::ContentType:      
    Email::MIME::Encodings:        
    Email::Simple:                 1.7
    Test::Deep:                    
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
