--- #YAML:1.0
name:               Email-MIME-Modifier
version:            1.444
abstract:           Modify Email::MIME Objects Easily
author:
    - Casey West <casey@geeknest.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::MessageID:     1.2
    Email::MIME:          1.82
    Email::MIME::ContentType:  1.0
    Email::MIME::Encodings:  1.313
    Email::Simple:        1.92
    Test::More:           0.47
resources:
    repository:  http://github.com/rjbs/email-mime-modifier
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
